# Pipeline to build and deploy controlDB for ELT Framework https://github.com/bennyaustin/elt-framework
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - main
 paths:
   include:
     - elt-framework/ControlDB

pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio
  vmImage: windows-latest

stages:
  - stage: ci
    displayName: Build Stage
    jobs:
      - template: templates/build-sqldb.yml
        parameters:
          solutionName:  ControlDB
          buildPath:  elt-framework\ControlDB\bin\Release

  - stage: cd_nonprod
    displayName: Deploy Stage - Non Prod
    dependsOn: ci
    condition: succeeded()
    jobs:
    - template: templates/deploy-sqldb.yml
      parameters:
        serviceConnectionName:  devops-contoso-spn
        keyvaultName:  ba-kv01-kn3acb6lw3vr4 
        buildArtifactName:  dacpac
        targetDatabaseServer:  ba-sql01-kn3acb6lw3vr4.database.windows.net,1433
        targetDatabase:  controlDB

  - stage: cd_prod
    displayName: Deploy Stage - Prod
    dependsOn: ci
    condition: succeeded()
    jobs:
    - template: templates/deploy-sqldb.yml
      parameters:
        serviceConnectionName:  devops-contoso-spn
        keyvaultName:  ba-kv01-o5rium4bfcf6a 
        buildArtifactName:  dacpac
        targetDatabaseServer:  ba-sql01-o5rium4bfcf6a.database.windows.net,1433
        targetDatabase:  controlDB