name: ControlDB Database Objects Provisioning
on: workflow_dispatch 
jobs:
    release:      
      runs-on: windows-latest
      steps:
        - name: Checkout code 
          uses: actions/checkout@v3
        - name: Display checkout files and folders
          run: Get-ChildItem ${{github.workspace}} -Recurse
        - name: Azure Login
          uses: Azure/login@v1
          with:
           creds: '{"clientId":"${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }}","clientSecret":"${{ secrets.SERVICE_PRINCIPAL_CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
        - name: Install Azure CLI (Windows)
          run: |
            Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile AzureCLI.msi
            Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
            az --version
        - name: Build and Deploy SQL Database
          uses: Azure/sql-action@v2
          with:
            connection-string: ${{secrets.CONTROLDB_CONNECTIONSTRING}}
            path: ${{github.workspace}}\iac\ControlDB\Database.sqlproj
            action: 'Publish'
            arguments: '/p:DropPermissionsNotInSource=false /p:BlockOnPossibleDataLoss=false /p:DropRoleMembersNotInSource=false /p:DropObjectsNotInSource=false /p:IgnoreColumnOrder=true /p:IgnorePermissions=true'
        - name: Azure Logout
          run: |
            az logout
